#!/bin/bash
# -----------------------------------------------------------------------------
# colima.sh - Colima VM Management for Docker on macOS
# Copyright (c) 2025-2026, VIDAL & ASTUDILLO Ltda and contributors.
# www.vidalastudillo.com
#
# Manages a Colima VM hosted on an external SSD to keep heavy Buildroot
# build I/O off the internal disk.
#
# ENGINEERING DECISIONS:
# 1. CPUs: Default 4. Overridable via COLIMA_CPUS.
#    Reserves enough cores for the VM while leaving headroom for the host OS.
# 2. Memory: Default 10GB. Overridable via COLIMA_MEMORY.
#    Enough for parallel Buildroot compilation without causing host swap.
# 3. Disk: Default 100GB sparse file on the external SSD. Overridable via
#    COLIMA_DISK. Holds Docker images and layers only — build data lives on
#    the SSD directly (see Decision #8).
# 4. VZ + VirtioFS: Apple native virtualization stack for maximum I/O
#    performance, vital for thousands of small files generated by Buildroot.
# 5. Runtime: Rootful Docker (Colima default), allowing Buildroot to execute
#    mknod and chown during rootfs image creation.
# 6. Docker Plugins: Configures 'buildx' and 'compose' as the default plugins
#    to replace functionality lost after removing Docker Desktop.
# 7. Credential Helper: Automatically detects and fixes orphaned 'desktop'
#    credential helper settings left by Docker Desktop.
# 8. Workspace Volume: buildroot_workspace is a Docker local bind-mount volume
#    backed by $SSD_MOUNT/workspace. This keeps build data (CCache, downloads,
#    outputs) on the external SSD, independent of the Lima VM lifecycle.
#    Survives 'colima delete' and Colima/Docker updates.
#    COLIMA_HOME is exported to $SSD_DATA_PATH so Colima stores its instance
#    data on the SSD without requiring a ~/.colima symlink (which newer Colima
#    versions reject).
#
# OVERRIDABLE ENVIRONMENT VARIABLES:
#   COLIMA_SSD_NAME   Name of the external SSD volume (default: "Container Image")
#   COLIMA_CPUS       Number of CPUs for the VM (default: 4)
#   COLIMA_MEMORY     Memory in GiB for the VM (default: 10)
#   COLIMA_DISK       Disk size in GiB for the VM (default: 100)
# -----------------------------------------------------------------------------

set -e

# --- CONFIGURATION ---

# Resolve project root from the script's own location (scripts/ subdirectory)
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

SSD_NAME="${COLIMA_SSD_NAME:-Container Image}"
SSD_MOUNT="/Volumes/$SSD_NAME"
SSD_DATA_PATH="$SSD_MOUNT/colima-data"
WORKSPACE_SSD_DIR="$SSD_MOUNT/workspace"

# Direct Colima to store its data on the external SSD.
# COLIMA_HOME is the canonical env var supported by Colima; no symlink needed.
export COLIMA_HOME="$SSD_DATA_PATH"

# Resources (with environment variable overrides)
CPU_CORES=${COLIMA_CPUS:-4}
MEMORY_GB=${COLIMA_MEMORY:-10}
DISK_SIZE_GB=${COLIMA_DISK:-100}

# --- HELPER FUNCTIONS ---

log() { echo -e "\033[1;32m[containers]\033[0m $1"; }
warn() { echo -e "\033[1;33m[warning]\033[0m $1"; }
error() { echo -e "\033[1;31m[error]\033[0m $1"; exit 1; }

check_ssd() {
    if [ ! -d "$SSD_MOUNT" ]; then
        error "External SSD '$SSD_NAME' is not mounted at $SSD_MOUNT. Aborting to protect internal disk."
    fi
}


ensure_docker_context() {
    log "Ensuring Docker context and socket..."
    docker context use colima >/dev/null 2>&1 || docker context use default
    sudo ln -sf "$COLIMA_HOME/default/docker.sock" /var/run/docker.sock
}

check_docker_credentials() {
    # Detects and fixes orphaned 'credsStore': 'desktop' settings
    if [ -f "$HOME/.docker/config.json" ]; then
        CURRENT_STORE=$(grep '"credsStore":' "$HOME/.docker/config.json" | cut -d'"' -f4 || echo "")

        # 1. Fix orphaned Desktop setting
        if [ "$CURRENT_STORE" == "desktop" ]; then
            if ! command -v docker-credential-desktop >/dev/null 2>&1; then
                warn "Docker config points to 'desktop' credentials, but Docker Desktop is not installed."
                log "Fixing: Switching to 'osxkeychain' for Colima compatibility..."
                sed -i '' 's/"credsStore": "desktop"/"credsStore": "osxkeychain"/' "$HOME/.docker/config.json"
                CURRENT_STORE="osxkeychain"
            fi
        fi

        # 2. Verify existence of the selected helper
        if [ "$CURRENT_STORE" == "osxkeychain" ]; then
            if ! command -v docker-credential-osxkeychain >/dev/null 2>&1; then
                warn "Credential helper 'osxkeychain' is configured but NOT installed."
                warn "Please run: brew install docker-credential-helper"
            fi
        fi
    fi
}

ensure_workspace_volume() {
    # Creates buildroot_workspace as a bind-mount volume backed by the SSD directory.
    # If the volume exists but points elsewhere, it is recreated.
    local device
    device=$(docker volume inspect buildroot_workspace --format '{{ index .Options "device" }}' 2>/dev/null || true)
    if [ "$device" = "$WORKSPACE_SSD_DIR" ]; then
        log "Workspace volume: OK."
        return 0
    fi
    if docker volume inspect buildroot_workspace >/dev/null 2>&1; then
        warn "Workspace volume exists but is not SSD-backed. Recreating..."
        docker volume rm buildroot_workspace
    fi
    log "Creating workspace volume at $WORKSPACE_SSD_DIR..."
    docker volume create \
        --driver local \
        --opt type=none \
        --opt device="$WORKSPACE_SSD_DIR" \
        --opt o=bind \
        buildroot_workspace
}

configure_plugins() {
    log "Configuring Docker plugins (buildx/compose)..."
    PLUGIN_DIR="$HOME/.docker/cli-plugins"
    mkdir -p "$PLUGIN_DIR"

    # Buildx configuration
    if brew list docker-buildx >/dev/null 2>&1; then
        ln -sfn "$(brew --prefix)/opt/docker-buildx/bin/docker-buildx" "$PLUGIN_DIR/docker-buildx"
    else
        warn "docker-buildx not found. Please run 'brew install docker-buildx' first."
    fi

    # Compose configuration (v2)
    if brew list docker-compose >/dev/null 2>&1; then
        ln -sfn "$(brew --prefix)/opt/docker-compose/bin/docker-compose" "$PLUGIN_DIR/docker-compose"
    else
        warn "docker-compose not found. Please run 'brew install docker-compose' first."
    fi
}

show_usage() {
    echo "Usage: $0 {setup|up|stop|status}"
    echo ""
    echo "Manages a Colima VM stored on an external SSD (default: '$SSD_NAME')."
    echo "Override the SSD name with COLIMA_SSD_NAME. Override resources with"
    echo "COLIMA_CPUS, COLIMA_MEMORY, COLIMA_DISK."
    echo ""
    echo "Options:"
    echo "  setup   Initial configuration. Run once: creates the VM on the SSD,"
    echo "          configures Docker plugins (buildx/compose), and creates the"
    echo "          buildroot_workspace volume backed by the SSD workspace directory."
    echo "          Defaults: $CPU_CORES CPUs, ${MEMORY_GB}GB RAM, ${DISK_SIZE_GB}GB VM disk."
    echo "  up      Starts the infrastructure if not already running."
    echo "          Validates SSD presence and workspace volume. Use for daily startup."
    echo "  stop    Cleanly shuts down the VM. Run before disconnecting the SSD."
    echo "  status  Shows VM status, workspace size on SSD, and active Docker context."
    echo ""
}

# --- MAIN COMMANDS ---

do_setup() {
    log "Starting initial configuration (SETUP)..."
    check_ssd
    mkdir -p "$SSD_DATA_PATH" "$WORKSPACE_SSD_DIR"

    # Flags verified against 'colima start --help':
    # --cpus: number of CPUs
    # --memory: memory in GiB
    # --disk: disk size in GiB (for Docker images/layers only)
    # --vm-type: virtual machine type (vz)
    # --mount-type: volume driver for the mount (virtiofs)
    # --mount: host directories exposed inside the VM (path:writable)
    colima start \
        --cpus $CPU_CORES \
        --memory $MEMORY_GB \
        --disk $DISK_SIZE_GB \
        --vm-type vz \
        --mount-type virtiofs \
        --mount "$PROJECT_ROOT:w" \
        --mount "$WORKSPACE_SSD_DIR:w"

    ensure_docker_context
    check_docker_credentials
    configure_plugins
    ensure_workspace_volume
    log "Setup completed successfully."
}

do_up() {
    check_ssd

    if colima status 2>&1 | grep -q "is running"; then
        log "Infrastructure is already running."
    else
        log "Starting infrastructure..."
        colima start \
            --cpus $CPU_CORES \
            --memory $MEMORY_GB \
            --disk $DISK_SIZE_GB \
            --vm-type vz \
            --mount-type virtiofs \
            --mount "$PROJECT_ROOT:w" \
            --mount "$WORKSPACE_SSD_DIR:w"
        ensure_docker_context
        check_docker_credentials
        log "Infrastructure is ready."
    fi
    ensure_workspace_volume
}

do_stop() {
    log "Performing clean shutdown..."
    colima stop || warn "Shutdown command failed or VM was already stopped."
    log "Shutdown process finished."
}

do_status() {
    check_ssd
    log "Colima VM Status:"
    colima status || true
    echo "---"
    log "Workspace (SSD):"
    if [ -d "$WORKSPACE_SSD_DIR" ]; then
        du -sh "$WORKSPACE_SSD_DIR"
    else
        warn "Workspace directory not found at $WORKSPACE_SSD_DIR. Run: ./scripts/colima.sh setup"
    fi
    echo "---"
    log "Active Docker Context:"
    docker context ls | grep "*"
}

# --- ENTRYPOINT ---

case "$1" in
    setup)  do_setup ;;
    up)     do_up ;;
    stop)   do_stop ;;
    status) do_status ;;
    *)      show_usage ;;
esac
